language: python
python: 2.7
sudo: true
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
matrix:
  allow_failures:
  - env: PLONE_VERSION=5.0
  fast_finish: true
before_install:
  - sudo apt-get install python-dev libldap2-dev libsasl2-dev libssl-dev
  - wget http://downloads.buildout.org/2/bootstrap.py -O bootstrap.py
script:
  - false
after_success:
  - bin/createcoverage
  - pip install -q coveralls
  - coveralls
