language: python
python: 2.7
sudo: false
cache:
  directories:
    - buildout-cache
env:
- PLONE_VERSION=4.2
- PLONE_VERSION=4.3
- PLONE_VERSION=5.0
matrix:
  allow_failures:
  - env: PLONE_VERSION=5.0
  fast_finish: true
addons:
  apt:
  - python-dev
  - libldap2-dev
  - libsasl2-dev
  - libssl-dev
script:
- false
